### ISSUE TITLE
Update setup instructions

### ISSUE THREAD

**Issue by cforgaci** [carpentries-incubator/r-geospatial-urban#33]
Update setup instructions according to the feedback received and issues observed during the workshop:
- [ ] Installation information is shown both in the table at the top of the setup page and in the callout blocks further down on the page. To avoid confusion, remove the table and make sure installation instructions are easily found in one place.
- [ ] Specify versions of all software to be installed as well as system requirements (e.g., minimum OS versions)
- [ ] Test new setup instructions on macOS, Windows and Linux
- [ ] Consider also #11

**Comment by manuGil** [comment]
@cforgaci Hello Claudiu. Sure, I can help you with GitHub actions. We can meet for that next Monday or Thursday. 
I am curious about the RStudio Server, could you pleas make an account for me?

**Comment by Selkubi** [comment]
I'm also interested to see how an RStudio Server works! Can you create an account for me too? 

I don't have much experience with GitHub actions though. Sounds intriguing.

**Comment by cforgaci** [comment]
@Selkubi, would you like to draft a cleaner setup page? You know the workflow and versions used in the github action as well as the issues we had with this page in the workshop. If you want to do this, please do so in a branch `33-setup-sk` (<issue_no>-<topic>-<initials>) and a PR from there. We can then iterate on it together.
