### ISSUE TITLE
Guidelines for creating location-specific lesson data

### ISSUE THREAD

**Issue by cforgaci** [carpentries-incubator/r-geospatial-urban#42]
We can offer this as an alternative to those who want to use a datastet that is more relatable for their participants.

**Comment by ana-5r** [comment]
For future refence: 
Free Geospatial Data Resources (Ebook)
https://buymeacoffee.com/ochwada/e/203469

Another categorised list of free GIS datasets: 
https://freegisdata.rtwilson.com/
