### ISSUE TITLE
Rendering headings that include a code block

### ISSUE THREAD

**Issue by manuGil** [carpentries-incubator/r-geospatial-urban#6]
I noticed that some headings do not render well when they include a code bloke. 
For example, the following Rmarkdown snipped produces a heading without white spaces between **sf** and adjacent words:

```r
# The `sf` package

`sf` stands for Simple Features which is a standard defined by the Open Geospatial Consortium for storing and 
accessing geospatial vector data. PostGIS uses the same standard; so those of you who used PostGIS, might
find some resemblances with the functions used by the `sf` package. 
```

Results:
<img width="449" alt="Screenshot 2024-01-08 at 19 18 21" src="https://github.com/carpentries-incubator/r-geospatial-urban/assets/8195424/c75f3291-8a22-43d2-8361-6eec1d33cdfe">

The core of the issue is that the Rmarkdown parser removes any white spaces at the beginning and end of a string surrounded by backticks (`). [Explained here](https://meta.stackoverflow.com/questions/297113/how-to-insert-a-space-as-a-first-character-inside-of-backticks-in-comments)

 I tried several ways to trick the parser, but they did not work. Notice this only affects the headings and not the paragraph below the heading. This might be because headings and paragraphs have different styles.

**I suggest we avoid using code blocks in the headings so that white spaces are rendered properly.** For example, using `# The 'sf' Package` instead. Note that this will rendered the heading using uppercase (that's define by the style template), but it will maintain the white spaces.

**Comment by cforgaci** [comment]
This is strange. This is how it looks like for me: 
<img width="753" alt="image" src="https://github.com/carpentries-incubator/r-geospatial-urban/assets/33600128/d76de1f1-73a0-4607-870d-331132895bf5">

**Comment by manuGil** [comment]
Maybe I am missing the formatting templates or I have a different version of the formatting packages.
